### ISSUE TITLE
Change key bindings for "Go back" and "Go next".

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf-compass#101]
Why doesn't Compass use Command-left_arrow and Command-right_arrow instead of Command-[ and Command-]?

**Comment by jreadey** [comment]
Wierd - neither works for me on the Mac.

**Comment by giumas** [comment]
On MAC the solution is here: http://osdir.com/ml/wxpython-users/2013-08/msg00118.html
I have modified the keys (https://github.com/HDFGroup/hdf-compass/pull/133) so that:

* go back: CTRL(or APPLE) + Left 
* go next: CTRL(or APPLE) + Right
* go up: CTRL(or APPLE) + Up
* go top: CTRL(or APPLE) + SHIFT + Up
