### ISSUE TITLE
Drag and drop to Toolbar broken

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#116]
With the latest binary install image for Mac (https://s3.amazonaws.com/hdfgroup.download/HDFCompass/latest/hdfcompass-latest-macosx.dmg), drag and drop to the toolbar icon is not working.

This is a regression from the previous release.  Likely it is due to the switch to pyinstaller from py2app for creating the binary.

**Comment by giumas** [comment]
There is an open ticket: https://github.com/pyinstaller/pyinstaller/issues/1309

**Comment by giumas** [comment]
@jreadey Are you sure that the drag-and-drop to the toolbar icon was working with py2app? 

I am asking since I have found a workaround to the py2app issue with ``hydroffice.bag`` (https://github.com/HDFGroup/hdf-compass/issues/107), but in the frozen application the drag and drop does not work!

I have looked on the `setup.py2app.py` (was `setup.py`) and there is this part:

    # ARGV emulation interacts badly with wxPython on Mac... it "eats" events
    # when the program starts up and causes windows not to be displayed.
    OPTIONS = { 'argv_emulation': False,

that was added by @andrewcollette with this commit:

```
commit 6f548861d4c0277547f123720292eb15f394fa56
Author: Andrew Collette <andrew.collette@gmail.com>
Date:   Sun Apr 26 11:09:59 2015 -0600

    Address a number of GUI issues on OS X
```

If this is the case, this is not a new regression.

**Comment by giumas** [comment]
And I believe that this may be a duplication of https://github.com/HDFGroup/hdf-compass/issues/24, or at least both tickets could be merged (in case that we want to support the Drag&Drop also on Linux and Windows).

**Comment by jreadey** [comment]
I couldn't reproduce with the py2app install image.
Closing this and will use #24 to track drag and drop issues.
