### ISSUE TITLE
Windows XP Support?

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#153]
Working with another project, I discovered that WxPython 3.0.0 has an issue with Windows XP: http://wxpython-users.1045709.n5.nabble.com/XP-crash-fixed-or-worked-around-at-least-td5719699.html

The issue is a bit tricky to debug since it just makes the Wx-based application crash with quite a cryptic Windows error.

So, if HDF Compass has to also support Win XP, the minimum WxPython suggested in the documentation should be changed to 3.0.1.

**Comment by giumas** [comment]
This ticket may interfere with https://github.com/HDFGroup/hdf-compass/issues/151

**Comment by jreadey** [comment]
I've been releasing the frozen binaries for Windows based on Windows 7, so it makes since to treat Windows 7 as the minimal OS for HDF Compass on Windows.  XP and Vista are not officially supported by Microsoft in any case (and together are less than 10% of the Windows install base).

I've updated the Readme to explicitly state that Windows 7 or greater is the requirement.

**Comment by jreadey** [comment]
I've been using wxpython 3.0.2.0 on the build machines.  Is there any issue with just requiring that specific version for HDF Compass?

**Comment by giumas** [comment]
I think that is a good choice. I believe that currently is the most stable version of wxpython.

**Comment by giumas** [comment]
Incidentally, it also makes HDF Compass work on XP (although I understand that Win7 is the minimal Windows OS).
