### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by QuLogic** [HDFGroup/hdf-compass#46]
For such a new project, there should be no reason why it can't support both 2 and 3.

**Comment by mdraw** [comment]
I think the reason (or at least one of them) is the dependency Pydap, which is not Python 3 compatible yet and doesn't seem to be updated any more: https://github.com/robertodealmeida/pydap/issues/7

**Comment by QuLogic** [comment]
That's unfortunate, but no reason not to make this one prepared for it.

And actually, I was really just gauging interest; it's not that difficult for me to open some PRs for it.

**Comment by davidtrem** [comment]
Yes, python 3 support please :+1:

**Comment by jreadey** [comment]
If the file plugins get imported dynamically (currently they are static imports), I guess it would be feasible to just ignore plugins that aren't python 3 compliant.  That would likely make the pyinstaller more tricky though.

**Comment by QuLogic** [comment]
That is not difficult to accomplish. If dependencies are not available, simply don't register the plugin.

**Comment by QuLogic** [comment]
It looks like the biggest hindrance is going to be wxPython, which is lagging behind pretty much every toolkit WRT Python 3 bindings.

**Comment by giumas** [comment]
Is there a reason that stops by adding: `from __future__ import absolute_import, division, print_function, unicode_literals` at the top of each module and modify the code as required? If not, is there a branch where a similar work is in progress?

**Comment by QuLogic** [comment]
To make for smaller and easier-to-review PRs. But there is no other work because upstream here does not seem to be showing any interest.

**Comment by giumas** [comment]
@QuLogic: Have you been able to run HDFCompass on Python 3? Using the last wxPython night-built wheels, I have found that there is a open ticket with Matplotlib and the Phoenix backend: https://github.com/matplotlib/matplotlib/pull/3421 
I am currently on Windows using mpl 1.4.3, but the patch should be still in dev: http://stackoverflow.com/questions/31467759/missing-wxversion-when-using-matplotlib-with-wxpython-phoenix-in-python3

**Comment by QuLogic** [comment]
No, sorry; I have not done much more. I would be happy to continue if upstream showed some interest, but I'm not going to waste time on fruitless endeavours.

**Comment by jreadey** [comment]
I'd be interested in hearing from anyone who got HDFCompass running on Python 3.  Right now I'm a little hesitant to invest time to it since there seems there's a high probability of hitting issues with other packages.

Failing some positive evidence to support Python 3 (like the wxPython issue being closed), I'd like to focus on functionality in the app for now and do Python 3 at a latter date.

Once Python 3 is enabled the question becomes do we continue to support backward compatibility with Python 2 or just become a Python 3 only package.  As an application (rather than a library that other Python 2 packages may depend on), I assume most people would be fine with Python 3 only.

**Comment by giumas** [comment]
@jreadey , I totally agree with your point. My intent was to just evaluate the amount of work involved to reach the Python 3 portability before splitting it in small PRs. Since the application is relatively small, I believe that there is not so much of work (several `print` statements, the substitution of `cStringIO` with `BytesIO`, ...).

However, given the current Matplotlib (1.4.3) issue with the `wxAgg` backend, I would suggest to wait the next release (1.5.0) to reconsider the situation. (I don't really want to re-open here the never-ending battle between wx and Qt, but I would be curious to know the reason of the wx selection for this project.)

Given that there are many libraries that are still Py2-only as well as that the price to maintain Python 2-3 portability is quite low, I would suggest to maintain once obtained for a while.

@QuLogic: what are your thoughts on this?

**Comment by QuLogic** [comment]
A naive translation is:
```
$ git di --shortstat 
 11 files changed, 30 insertions(+), 17 deletions(-)
```
It is positively tiny. Of course, if going for 2/3 compatibility, there should be a few other changes, but not too many. Based on matplotlib's PR, you will have more problems porting to wxPython-Phoenix.

**Comment by giumas** [comment]
Using matplotlib 1.5.0rc3 and wxPython 3.0.3.dev, I have been able to run the app for the first time:

![capture](https://cloud.githubusercontent.com/assets/2849257/10749785/7fb409e8-7c44-11e5-8a88-62dd2a1108dd.PNG)

However, there are several issues related to the migration from 'classic' wxPython to Phoenix (some of them listed here: http://wxpython.org/Phoenix/docs/html/MigrationGuide.html) that would require a certain number of conditional statements (given that the back compatibility has been broken in multiple ways).

Apart from polluting the code with these statements, at today there is still not a 'stable' cross-platform Phoenix release for Python 3. 

Thus, I am closing this ticket as 0.6.0 milestone, and I would propose to open a new one for Phoenix adoption once that a stable py3 version will be released.

**Comment by jreadey** [comment]
@giumas - thanks for checking this out.  We'll re-evaluate switching to Python3 for a future releases.

**Comment by giumas** [comment]
After ``wxPython``/``matplotlib``, ``pydap`` is the other blocking dependency to move to py3. Hopefully, this issue should be solved in the short term: https://github.com/robertodealmeida/pydap/issues/14
