### ISSUE TITLE
Display Object hierarchy in Tree

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#66]
Use Tree Control to display nodes.

**Comment by giumas** [comment]
@hyoklee and @jreadey : From my understanding, the 'issue26' branch is also taking care of this enhancement. I tested it days ago, and it was working very well.. Now the branch has additional stuff about the graph.

What about to split the PR so that we can test this Tree Control feature indepedently from https://github.com/HDFGroup/hdf-compass/issues/26?

This is also because the tree view of data structures with WxPython is quite main stream.. while it is less the case for a graph view (thus the need to use also another library). 

In my personal opinion, I believe that not all the users will really enjoy the graph (it seems to be for a more specialized type of user). The tree provides a good idea of the data structure for a large number of use cases.

**Comment by giumas** [comment]
Can we resurrect the 'issue26' branch and do that split that I was proposing a while ago? I would vote for small improvements today rather than big enhancement never! :)
