### ISSUE TITLE
Clicking  an HDF5 bitfield dataset doesn't show anything

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#99]
1) File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/ntypes.h5

2) Testing version: Windows version of the release candidate from S3

Clicking an HDF5 bitfield dataset(bitfield_type_1) doesn't pop up a new windows to show the data. Does compass support HDF5 bitfield type? If not, may generate a windows say"compass doesn't support HDF5 bitfield type now".  Now nothing happens if I click bitfield_type_1. It makes me wonder if HDF5compass is frozen.

h5dump output:

DATASET "bitfield_type_1" {
      DATATYPE  H5T_STD_B32BE
      DATASPACE  SIMPLE { ( 8 ) / ( 8 ) }
      DATA {
      (0): fc:fd:fe:ff, f8:f9:fa:fb, f4:f5:f6:f7, f0:f1:f2:f3, ec:ed:ee:ef,
      (5): e8:e9:ea:eb, e4:e5:e6:e7, e0:e1:e2:e3
      }
   }

**Comment by giumas** [comment]
@kyang2014 why do you prefer to open a new issue for each variation on the same problem? 

@jreadey what about closing all these similar issues and collect them under a couple of tickets? I am getting confused with all these open tickets ... and they can be solved in a couple of PRs.

I don't also understand the reference to h5dump.. we know that the test files are correct.

Why don't we work on closing tickets by PRs rather than keep opening new ones? ;)

**Comment by kyang2014** [comment]
John,

I don't quite understand what you mean. I collected the similar issue with one ticket(for example, the unknown type issue applies to all the datatypes https://github.com/HDFGroup/hdf-compass/issues/95). To me if something is wrong with displaying values for one specific HDF5 datatype, it should be a new issue, They are not variations of the same problem. 

However, if you want me to do this in a different way, I can collect issues according to datatype/dataspace/etc.  Please advise.  Otherwise, I will continue with what I feel that makes sense. 
Also the h5dump output is a good reference to me and I think for people who want to have a sense what may be wrong at a first quick look. If you don't think that's helpful, I will not provide them from now on. 

What's the meaning of PR? Sorry, don't understand.

**Comment by hyoklee** [comment]
PR is Pull Request - a GitHub jargon. By the way, @giumas is not @jreadey.

**Comment by kyang2014** [comment]
Thanks Joe . I am still a new comer of github. Sorry @jreadey for the mistaken identification.

**Comment by jreadey** [comment]
I'll see if I can consolidate some of tickets @kyang2014 has opened.
Given that there's plenty to do for the identified release target, I'd recommend not addressing the usability issues in this go around.  Bitfield types aren't even supported in h5py, so that is likely not to be resolved anytime soon.
I do think the h5dump output is useful to see what the output looks like without downloading the file.

**Comment by kyang2014** [comment]
Fully agree that some of these issues are definitely for this release. I think(at least this is my major intention or contribution)  it definitely can help document the limitations or the compass can provide  a user-friendly message like “bitfield is not supported”, rather than “silently sitting there”. This will make users confused. So these issues can at least help documenting the limitations of the tool for this release.

I found an issue with another cornered datatype. A 128-bit floating-point HDF5 dataset. Compass cannot open this file. h5dump can. Do you want me to submit an issue?

**Comment by jreadey** [comment]
@kyang2014 - it's great to document these, but I want to keep the number of open issues at a manageable level and targeted mainly I things we expect to be working on for this or the next release.

Go ahead and create a ticket for the 128 bit float issue.  I'll link it to my issue #102 tracking and we'll keep track of it from there.

**Comment by jreadey** [comment]
Closing this on tracking via #102.
